version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/iw
      SPRING_DATASOURCE_USERNAME: iw
      SPRING_DATASOURCE_PASSWORD: iw
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - spring-postgres

  postgres:
    image: postgres:13
    container_name: postgres-develop
    environment:
      POSTGRES_USER: iw
      POSTGRES_PASSWORD: iw
      POSTGRES_DB: iw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-postgres

networks:
  spring-postgres:

volumes:
  postgres_data:
